dist: precise
sudo: required
language: php

php: 5.6

before_script:
- composer self-update
- composer install
- export PATH="/home/travis/build/iriberri/travis-experiments/vendor:$PATH"

script:
  - phpunit --version
