
install: true
sudo: true
script: 
- apt-key list
- curl https://cli-assets.heroku.com/install-ubuntu.sh | sh
- apt-key list
- sudo apt-get update

language: ruby


notifications:
  email:
    on_success: never # default: change
    on_failure: never # default: always
    on_change: never
